// Package pdfhash computes a conservative fingerprint for exported PDFs.
package pdfhash

import (
	"bytes"
	"compress/zlib"
	"crypto/sha256"
	"encoding/hex"
	"io"
	"regexp"
	"strconv"
)

var volatileMetadataFields = []*regexp.Regexp{
	// Document information dictionary dates.
	regexp.MustCompile(`(?s)/(?:ModDate|CreationDate|LastModified)\s*(?:\((?:\\.|[^\\)])*\)|<[^>]*>)`),
	// Annotation modification dates. Restrict this to PDF date strings because
	// /M may have other meanings in content outside an annotation dictionary.
	regexp.MustCompile(`(?s)/M\s*\(D:(?:\\.|[^\\)])*\)`),
	// The trailer ID is commonly regenerated by PDF exporters.
	regexp.MustCompile(`(?s)/ID\s*\[\s*<[^>]*>\s*<[^>]*>\s*\]`),
	// Equivalent timestamps in an XMP metadata stream.
	regexp.MustCompile(`(?is)<(?:xmp:)?(?:ModifyDate|CreateDate|MetadataDate)>.*?</(?:xmp:)?(?:ModifyDate|CreateDate|MetadataDate)>`),
	// BOOX generates a new sync commit ID even when note content is unchanged.
	regexp.MustCompile(`(?i)"commitId"\s*:\s*"[0-9a-f-]+"`),
}

var (
	resourceNamePattern = regexp.MustCompile(`/FX([EX])(\d+)([A-Z0-9]+)`)
	directLengthPattern = regexp.MustCompile(`/Length\s+(\d+)`)
	streamLengthPattern = regexp.MustCompile(`/Length\s+\d+`)
)

const maxDecodedStreamSize = 256 << 20

// Sum returns a SHA-256 fingerprint after removing only metadata fields that
// PDF exporters routinely regenerate. All page, annotation, stream, and
// structural bytes remain part of the fingerprint, so an unfamiliar change is
// conservatively treated as real rather than accidentally ignored.
func Sum(pdf []byte) string {
	resources := resourceNames(pdf)
	canonical := make([]byte, 0, len(pdf))
	cursor := 0
	for cursor < len(pdf) {
		stream := nextStream(pdf, cursor)
		if stream < 0 {
			canonical = append(canonical, normalizeOutside(pdf[cursor:], resources)...)
			break
		}

		bodyStart := streamBodyStart(pdf, stream+len("stream"))
		descriptorStart := bytes.LastIndex(pdf[cursor:stream], []byte("obj"))
		if descriptorStart < 0 {
			descriptorStart = cursor
		} else {
			descriptorStart += cursor + len("obj")
		}
		descriptor := pdf[descriptorStart:stream]
		bodyEnd, endStream := streamEnd(pdf, bodyStart, descriptor)
		if bodyEnd < 0 {
			canonical = append(canonical, normalizeOutside(pdf[cursor:], resources)...)
			break
		}

		canonical = append(canonical, normalizeOutside(pdf[cursor:bodyStart], resources)...)
		body := pdf[bodyStart:bodyEnd]
		if bytes.Contains(descriptor, []byte("/FlateDecode")) {
			if decoded, ok := decodeFlate(body); ok {
				body = decoded
			}
		}
		body = replaceResourceNames(body, resources)
		if bytes.Contains(descriptor, []byte("/Type/Metadata")) || bytes.Contains(descriptor, []byte("/Type /Metadata")) {
			body = removeVolatileMetadata(body)
		}
		digest := sha256.Sum256(body)
		canonical = append(canonical, []byte("<decoded-stream-sha256:")...)
		canonical = append(canonical, hex.EncodeToString(digest[:])...)
		canonical = append(canonical, '>')
		cursor = endStream
	}
	sum := sha256.Sum256(canonical)
	return hex.EncodeToString(sum[:])
}

func normalizeOutside(data []byte, resources map[string]string) []byte {
	normalized := removeVolatileMetadata(data)
	// Encoded stream size is not semantic once the decoded payload is hashed.
	normalized = streamLengthPattern.ReplaceAll(normalized, nil)
	return replaceResourceNames(normalized, resources)
}

func removeVolatileMetadata(data []byte) []byte {
	normalized := data
	for _, field := range volatileMetadataFields {
		normalized = field.ReplaceAll(normalized, nil)
	}
	return normalized
}

func replaceResourceNames(data []byte, resources map[string]string) []byte {
	return resourceNamePattern.ReplaceAllFunc(data, func(match []byte) []byte {
		parts := resourceNamePattern.FindSubmatch(match)
		key := string(parts[2]) + ":" + string(parts[3])
		id, ok := resources[key]
		if !ok {
			return match
		}
		return []byte("/FX" + string(parts[1]) + id)
	})
}

func resourceNames(pdf []byte) map[string]string {
	resources := make(map[string]string)
	next := 1
	for _, parts := range resourceNamePattern.FindAllSubmatch(pdf, -1) {
		key := string(parts[2]) + ":" + string(parts[3])
		if _, exists := resources[key]; exists {
			continue
		}
		resources[key] = "R" + strconv.Itoa(next)
		next++
	}
	return resources
}

func nextStream(pdf []byte, start int) int {
	for start < len(pdf) {
		rel := bytes.Index(pdf[start:], []byte("stream"))
		if rel < 0 {
			return -1
		}
		pos := start + rel
		beforeOK := pos == 0 || isPDFSpace(pdf[pos-1]) || pdf[pos-1] == '>'
		after := pos + len("stream")
		afterOK := after < len(pdf) && (pdf[after] == '\r' || pdf[after] == '\n')
		if beforeOK && afterOK {
			return pos
		}
		start = after
	}
	return -1
}

func streamBodyStart(pdf []byte, start int) int {
	if start < len(pdf) && pdf[start] == '\r' {
		start++
	}
	if start < len(pdf) && pdf[start] == '\n' {
		start++
	}
	return start
}

func streamEnd(pdf []byte, bodyStart int, descriptor []byte) (bodyEnd, afterEndStream int) {
	if matches := directLengthPattern.FindAllSubmatch(descriptor, -1); len(matches) > 0 {
		length, err := strconv.Atoi(string(matches[len(matches)-1][1]))
		candidate := bodyStart + length
		if err == nil && candidate <= len(pdf) {
			end := candidate
			for end < len(pdf) && isPDFSpace(pdf[end]) {
				end++
			}
			if bytes.HasPrefix(pdf[end:], []byte("endstream")) {
				return candidate, end + len("endstream")
			}
		}
	}

	rel := bytes.Index(pdf[bodyStart:], []byte("endstream"))
	if rel < 0 {
		return -1, -1
	}
	bodyEnd = bodyStart + rel
	for bodyEnd > bodyStart && (pdf[bodyEnd-1] == '\r' || pdf[bodyEnd-1] == '\n') {
		bodyEnd--
	}
	return bodyEnd, bodyStart + rel + len("endstream")
}

func decodeFlate(data []byte) ([]byte, bool) {
	r, err := zlib.NewReader(bytes.NewReader(data))
	if err != nil {
		return nil, false
	}
	defer r.Close()
	decoded, err := io.ReadAll(io.LimitReader(r, maxDecodedStreamSize+1))
	if err != nil || len(decoded) > maxDecodedStreamSize {
		return nil, false
	}
	return decoded, true
}

func isPDFSpace(b byte) bool {
	switch b {
	case 0, '\t', '\n', '\f', '\r', ' ':
		return true
	default:
		return false
	}
}
